apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-system # Move to istio-system for better visibility
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ .Values.domain }}"
    - "www.{{ .Values.domain }}"
    - "kiali.{{ .Values.domain }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-route
  namespace: dev
spec:
  hosts:
  - "{{ .Values.domain }}"
  - "www.{{ .Values.domain }}"
  gateways:
  - istio-system/main-gateway # Correctly reference the gateway in another namespace
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: api-gateway.dev.svc.cluster.local
        port:
          number: 8080
  - route:
    - destination:
        host: frontend.dev.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-route
  namespace: istio-system
spec:
  hosts:
  - "kiali.{{ .Values.domain }}"
  gateways:
  - main-gateway
  http:
  - route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
