apiVersion: v2
name: filebeat
description: Filebeat log shipper
type: application
version: 1.0.0
appVersion: 8.5.1
dependencies:
  - name: filebeat
    version: 8.5.1
    repository: https://helm.elastic.co
